export function About() {
  return (
    <div style={{marginTop:"100px"}}>
        <h1>About page</h1>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo adipisci nulla maxime impedit reprehenderit itaque voluptates aspernatur corrupti optio voluptas, culpa assumenda necessitatibus et in quasi! Alias rerum aliquam consequatur molestias dignissimos voluptate quis enim ex assumenda autem similique commodi numquam fugit ab harum, recusandae nisi tempore, porro perferendis voluptas eaque eligendi minima corporis? Dignissimos id velit voluptate dolor placeat illo magnam nobis eligendi ipsam modi a repellendus culpa nostrum voluptatum tempore pariatur corrupti perspiciatis quisquam veniam, praesentium exercitationem. Ipsam sed officiis expedita aut natus quisquam voluptatum, accusamus perferendis odit aperiam minus repellat dolor eligendi vel ab suscipit vitae unde quae iusto, atque possimus velit. Et rem fuga suscipit error nihil exercitationem quas modi iure tempora quod! Dolore molestias excepturi animi dolores illum quae blanditiis sint, error quibusdam aliquid? Qui adipisci repellat doloribus ratione voluptates labore soluta, temporibus ipsam amet reprehenderit quis sequi repellendus maiores blanditiis iure porro eveniet in.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum, nesciunt. Sed ullam velit, placeat fugiat facilis doloremque mollitia repellendus necessitatibus cupiditate ipsam ipsa sit accusamus accusantium, temporibus rem, pariatur unde illo? Voluptates, minus illum explicabo deserunt in quis, blanditiis accusantium saepe esse animi deleniti eum minima nihil dolore voluptatum corporis dicta voluptate debitis rem. Quisquam perspiciatis cupiditate error tenetur velit voluptate ullam vero nobis nisi sunt aliquid architecto ipsa, autem, dicta atque iste corrupti et inventore minima molestias? Rerum explicabo neque eligendi voluptates ab delectus officia architecto assumenda a odit unde, quo magnam et tenetur aliquam omnis? Pariatur, iure maxime.</p>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Harum beatae corrupti at, deserunt earum cupiditate rerum nemo quam, non perspiciatis debitis sapiente. Atque exercitationem dolore omnis, sapiente laborum nisi beatae provident fuga quidem vero sequi aspernatur officiis quam quisquam ducimus reprehenderit asperiores dolor! Alias rerum, numquam saepe quia quasi aliquam aspernatur. Harum accusantium tempore quia nostrum, tenetur voluptas ad quas incidunt nisi, mollitia, recusandae accusamus asperiores nesciunt soluta delectus magnam ut sapiente neque architecto dicta quibusdam excepturi? Voluptatum hic non illo sapiente fugit? Iste delectus laboriosam fuga suscipit quo! Hic aspernatur voluptas dicta consequuntur esse consectetur repellendus modi ut repudiandae!</p>
        <a href="/" className="fs-1 text-decoration-none">Home page</a>
    </div>
  )
}
